#!/usr/bin/env python

import sys
import json

if len(sys.argv) != 2:
    print "Usage: ess grep FIELD"
    exit(1)

field = sys.argv[1]

def _grep(e, fields, default_field=None):
    if e.has_key(fields[0]):
        field_value = e[fields[0]]
        fields = fields[1:]
    elif default_field is not None and e.has_key(default_field):
        field_value = e[default_field]
    else:
        return
    if len(fields) >= 1:
        _grep(field_value, fields)
    else:
        print field_value

def grep(e):
    _grep(e, field.split('/'), "_source")

res = json.load(sys.stdin)
map(grep, res["hits"]["hits"])
